{"version":3,"sources":["app/Exceptions.ts"],"names":[],"mappings":";;AAAA,KAAK,CAAC,eAAe,GAAG,EAAE,CAAC;AAE3B;IAMC;;;;;OAKG;IACH,YACkB,UAAkB,EAAE,EACpB,aAAsB,IAAI,EAC1C,cAAyB;QAFT,YAAO,GAAP,OAAO,CAAa;QACpB,eAAU,GAAV,UAAU,CAAgB;QAG3C,KAAK,CAAC,iBAAiB,CAAC,IAAI,EAAE,cAAc,IAAI,SAAS,CAAC,CAAC;IAC5D,CAAC;IAEM,QAAQ;QACd,4CAA4C;QAC5C,sBAAsB;QACtB,EAAE;QACF,gBAAgB;QAChB,sBAAsB;QACtB,MAAM,CAAC,IAAK,CAAC,IAAI,CAAC,UAAU,CAAC,CAAC,CAAC,UAAU,CAAC,CAAC,CAAC,OAAO,CAAE,KAAM,IAAI,CAAC,OAAO,CAAC,CAAC,CAAC,IAAI,CAAC,OAAO,CAAC,CAAC,CAAC,EAAG,OAAO,IAAI,CAAC,KAAK,EAAE,CAAC;IACjH,CAAC;CACD;AA5BD,8BA4BC;AAED;;;GAGG;AACH,uBAA+B,SAAQ,SAAS;IAE/C,YAAY,OAAgB;QAC3B,KAAK,CAAC,OAAO,EAAE,IAAI,EAAE,iBAAiB,CAAC,CAAC;QACxC,IAAI,CAAC,IAAI,GAAG,mBAAmB,CAAC;IACjC,CAAC;CACD;AAND,8CAMC;AAED;;;GAGG;AACH,oBAA4B,SAAQ,SAAS;IAE5C,YAAY,OAAgB;QAC3B,KAAK,CAAC,OAAO,EAAE,KAAK,EAAE,cAAc,CAAC,CAAC;QACtC,IAAI,CAAC,IAAI,GAAG,gBAAgB,CAAC;IAC9B,CAAC;CACD;AAND,wCAMC;AAED;;;GAGG;AACH,8BAAsC,SAAQ,SAAS;IAEtD,YAAY,OAAe,EAAE,OAAgB;QAC5C,KAAK,CAAC,iBAAiB,OAAO,iBAAiB,CAAC,OAAO,CAAC,CAAC,CAAC,OAAO,CAAC,CAAC,CAAC,EAAE,CAAC,EAAE,EAAE,KAAK,EAAE,wBAAwB,CAAC,CAAC;QAC5G,IAAI,CAAC,IAAI,GAAG,0BAA0B,CAAC;IACxC,CAAC;CACD;AAND,4DAMC;AAED;;GAEG;AACH,6BAAqC,SAAQ,SAAS;IAErD,YAAY,OAAgB;QAC3B,KAAK,CAAC,OAAO,EAAE,KAAK,EAAE,uBAAuB,CAAC,CAAC;QAC/C,IAAI,CAAC,IAAI,GAAG,yBAAyB,CAAC;IACvC,CAAC;CACD;AAND,0DAMC;AAED;;GAEG;AACH,4BAAoC,SAAQ,SAAS;IAEpD,YAAY,OAAgB;QAC3B,KAAK,CAAC,OAAO,IAAI,wCAAwC,EAAE,KAAK,EAAE,sBAAsB,CAAC,CAAC;QAC1F,IAAI,CAAC,IAAI,GAAG,wBAAwB,CAAC;IACtC,CAAC;CACD;AAND,wDAMC","file":"Exceptions.js","sourcesContent":["Error.stackTraceLimit = 20;\r\n\r\nexport class Exception implements Error {\r\n\r\n\tpublic stack: string;\r\n\tpublic name: string;\r\n\r\n\r\n\t/**\r\n\t * \r\n\t * @param message \r\n\t * @param isCritical \r\n\t * @param exceptionClass {class} The exception class to exclude from stacktrace.\r\n\t */\r\n\tconstructor(\r\n\t\t\tpublic readonly message: string = '',\r\n\t\t\tpublic readonly isCritical: boolean = true,\r\n\t\t\texceptionClass?: Function) {\r\n\r\n\t\tError.captureStackTrace(this, exceptionClass || Exception);\r\n\t}\r\n\r\n\tpublic toString(): string {\r\n\t\t// Ex 1: [Critical] A big mess has happened!\r\n\t\t//\t\t <stacktrace here>\r\n\t\t//\r\n\t\t// Ex 2: [Minor]\r\n\t\t//\t\t <stacktrace here>\r\n\t\treturn `[${ (this.isCritical ? 'Critical' : 'Minor') }] ${ this.message ? this.message : '' } \\n ${this.stack}`;\r\n\t}\r\n}\r\n\r\n/**\r\n * Represents a serious problem that may cause the system in unstable state \r\n * and need restarting.\r\n */\r\nexport class CriticalException extends Exception {\r\n\r\n\tconstructor(message?: string) {\r\n\t\tsuper(message, true, CriticalException);\r\n\t\tthis.name = 'CriticalException';\r\n\t}\r\n}\r\n\r\n/**\r\n * Represents an acceptable problem that can be handled \r\n * and the system does not need restarting.\r\n */\r\nexport class MinorException extends Exception {\r\n\r\n\tconstructor(message?: string) {\r\n\t\tsuper(message, false, MinorException);\r\n\t\tthis.name = 'MinorException';\r\n\t}\r\n}\r\n\r\n/**\r\n * Represents an error where the provided argument of a function or constructor\r\n * is not as expected.\r\n */\r\nexport class InvalidArgumentException extends Exception {\r\n\r\n\tconstructor(argName: string, message?: string) {\r\n\t\tsuper(`The argument \"${argName}\" is invalid! ${(message ? message : '')}`, false, InvalidArgumentException);\r\n\t\tthis.name = 'InvalidArgumentException';\r\n\t}\r\n}\r\n\r\n/**\r\n * Represents an error when an unimplemented method is called.\r\n */\r\nexport class NotImplementedException extends Exception {\r\n\t\r\n\tconstructor(message?: string) {\r\n\t\tsuper(message, false, NotImplementedException);\r\n\t\tthis.name = 'NotImplementedException';\r\n\t}\r\n}\r\n\r\n/**\r\n * Represents an error when an unimplemented method is called.\r\n */\r\nexport class InternalErrorException extends Exception {\r\n\t\r\n\tconstructor(message?: string) {\r\n\t\tsuper(message || 'An error occured on the 3rd-party side', false, InternalErrorException);\r\n\t\tthis.name = 'InternalErrorException';\r\n\t}\r\n}"]}